# @package _global_
defaults:
    - template: panopli_paper

template:
    dataset_class: multi_frame_mos # many object scenes
    dataset_root: "data/large_corridor_500"
    # experiment: CONTRASTIVE_LIFT_learned_covariance_v2_no_regularization_on_covariance_smaller_clamp
    experiment: CONTRASTIVE_LIFT_multi_view_single_batch


    max_epoch: 9
    late_semantic_optimization: 2
    instance_optimization_epoch: 2 # 2+2=4
    segment_optimization_epoch: 4 # 2+4=6
    weight_class_0: 1.0
    
    max_depth: 50

    instance_loss_mode: "slow_fast"
    optimize_instance_only: True
    use_DINO_style: True
    use_proj: False
    use_delta: False
    temperature: 100.0
    max_instances: 6

    resume: null